name: Playwright Scraper

on:
  push:
    branches: [main]
  workflow_dispatch:   # <-- permite correr manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright asyncio

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run scraper
        run: |
          python scraper.py
